### PR TITLE
Use python3, add examples

### PR DESCRIPTION
**Pull request by mritzco**
1) Small modifications so things run smoothly on systems with python 2.x & 3.x installed
2) Add a basic example for motor and migrate the line following robot to python

The original JS code doesn't use the matrix and there's no much info on the valid ranges the components can return so it just uses similar code and works when tested on a track.

### CODE REVIEW

**Comment by RogueM** [comment]
Your change to the interpreter lines will break passing to the right command when only python 2 is present, such as is the case on Raspbian Lite.

... if users want to use those scripts with Python 3 by default, they should either:
- declare python3 as their preferred version interpreter system wide
- alias the python3 command to python
- passing the script to the desired command, python3

**Comment by mritzco** [comment]
Ah I see, code didn't run at all for me on python 2.7, and all online solutions pointed to requiring version 3 so I thought you didn't support version 2.

**Comment by RogueM** [comment]
No, it definitely should work on python 2. Regardless, if in the future you needed or wanted to use Python 3, add `alias python=python3` to your ~/.bashrc and it should start using python3 by default (there are other ways to enforce python3, but this is the least intrusive IMO).

But anyhow, if you get errors with python 2 post the details about those + your system details and we should be able to troubleshoot the problem and get it resolved.

**Comment by mritzco** [comment]
Ok, thanks!

**Pull request closed without merging**
